{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Overview\n",
    "We will tune and pilot with the 500 most frequent monosyllabic words from TASA."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-08-09 15:43:15.797802: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n",
      "2024-08-09 15:43:15.807121: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
      "2024-08-09 15:43:15.818023: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
      "2024-08-09 15:43:15.821123: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
      "2024-08-09 15:43:15.829169: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
      "To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-08-09 15:43:16.460718: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n"
     ]
    }
   ],
   "source": [
    "# python: base (3.11.4)\n",
    "# updated cuda drivers for GPU implementation\n",
    "\n",
    "import numpy as np\n",
    "import json\n",
    "import pandas as pd\n",
    "import time\n",
    "import tensorflow as tf\n",
    "\n",
    "from tensorflow.keras import backend as K\n",
    "from tensorflow.keras.optimizers import Adam\n",
    "\n",
    "from src.learner import *\n",
    "from utilities import *\n",
    "\n",
    "# data\n",
    "kidwords = pd.read_csv('data/kidwords/kidwords.csv', header=None)[0].tolist()\n",
    "\n",
    "top_500 = pd.read_csv('data/top_500.csv')\n",
    "train_word_indices = np.array([i for i, e in enumerate(kidwords) if e in top_500])\n",
    "\n",
    "XX = np.genfromtxt('data/kidwords/orth.csv', delimiter=\",\")\n",
    "YY = np.genfromtxt('data/kidwords/phon.csv', delimiter=\",\")\n",
    "\n",
    "non_zero_a = np.any(XX != 0, axis=0)\n",
    "X = XX[:, non_zero_a]\n",
    "\n",
    "non_zero_b = np.any(YY != 0, axis=0)\n",
    "Y = YY[:, non_zero_b]\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "GPU check"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Num GPUs Available:  1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\n",
      "I0000 00:00:1723236199.136306   54382 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "I0000 00:00:1723236199.157634   54382 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "I0000 00:00:1723236199.157775   54382 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n"
     ]
    }
   ],
   "source": [
    "print(\"Num GPUs Available: \", len(tf.config.list_physical_devices('GPU')))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Tune round #2\n",
    "We didn't get to the limit in tuning in round 1, so we are trying another round."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Configuration currently training: 0.001 6 60 20\n",
      "Epoch 1/60\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "I0000 00:00:1723233517.254928   39425 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "I0000 00:00:1723233517.255118   39425 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "I0000 00:00:1723233517.255185   39425 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "I0000 00:00:1723233517.351348   39425 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "I0000 00:00:1723233517.351483   39425 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "I0000 00:00:1723233517.351554   39425 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355\n",
      "2024-08-09 14:58:37.351625: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2021] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 6213 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3070 Ti Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6\n",
      "/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.\n",
      "  super().__init__(activity_regularizer=activity_regularizer, **kwargs)\n",
      "WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\n",
      "I0000 00:00:1723233517.915221   40117 service.cc:146] XLA service 0x7f2a50008480 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:\n",
      "I0000 00:00:1723233517.915243   40117 service.cc:154]   StreamExecutor device (0): NVIDIA GeForce RTX 3070 Ti Laptop GPU, Compute Capability 8.6\n",
      "2024-08-09 14:58:37.928128: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.\n",
      "2024-08-09 14:58:38.000631: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:531] Loaded cuDNN version 8907\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[1m266/479\u001b[0m \u001b[32m━━━━━━━━━━━\u001b[0m\u001b[37m━━━━━━━━━\u001b[0m \u001b[1m0s\u001b[0m 570us/step - binary_accuracy: 0.7114 - loss: 0.5828 - mse: 0.1993"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "I0000 00:00:1723233518.561872   40117 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m2s\u001b[0m 1ms/step - binary_accuracy: 0.7589 - loss: 0.5180 - mse: 0.1729 \n",
      "Epoch 2/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 550us/step - binary_accuracy: 0.8696 - loss: 0.3044 - mse: 0.0927\n",
      "Epoch 3/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 567us/step - binary_accuracy: 0.9021 - loss: 0.2441 - mse: 0.0724\n",
      "Epoch 4/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 533us/step - binary_accuracy: 0.9206 - loss: 0.2010 - mse: 0.0587\n",
      "Epoch 5/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 539us/step - binary_accuracy: 0.9346 - loss: 0.1689 - mse: 0.0486\n",
      "Epoch 6/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 583us/step - binary_accuracy: 0.9456 - loss: 0.1450 - mse: 0.0411\n",
      "Epoch 7/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 556us/step - binary_accuracy: 0.9529 - loss: 0.1277 - mse: 0.0358\n",
      "Epoch 8/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 485us/step - binary_accuracy: 0.9581 - loss: 0.1152 - mse: 0.0321\n",
      "Epoch 9/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 493us/step - binary_accuracy: 0.9619 - loss: 0.1059 - mse: 0.0294\n",
      "Epoch 10/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 515us/step - binary_accuracy: 0.9642 - loss: 0.0988 - mse: 0.0274\n",
      "Epoch 11/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 493us/step - binary_accuracy: 0.9663 - loss: 0.0932 - mse: 0.0257\n",
      "Epoch 12/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 516us/step - binary_accuracy: 0.9680 - loss: 0.0886 - mse: 0.0244\n",
      "Epoch 13/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 568us/step - binary_accuracy: 0.9694 - loss: 0.0849 - mse: 0.0234\n",
      "Epoch 14/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 576us/step - binary_accuracy: 0.9704 - loss: 0.0819 - mse: 0.0226\n",
      "Epoch 15/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 518us/step - binary_accuracy: 0.9713 - loss: 0.0793 - mse: 0.0218\n",
      "Epoch 16/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 552us/step - binary_accuracy: 0.9720 - loss: 0.0771 - mse: 0.0213\n",
      "Epoch 17/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 576us/step - binary_accuracy: 0.9724 - loss: 0.0753 - mse: 0.0208\n",
      "Epoch 18/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 526us/step - binary_accuracy: 0.9729 - loss: 0.0737 - mse: 0.0204\n",
      "Epoch 19/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 553us/step - binary_accuracy: 0.9733 - loss: 0.0723 - mse: 0.0200\n",
      "Epoch 20/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 549us/step - binary_accuracy: 0.9738 - loss: 0.0711 - mse: 0.0197\n",
      "Epoch 21/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 542us/step - binary_accuracy: 0.9742 - loss: 0.0701 - mse: 0.0194\n",
      "Epoch 22/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 524us/step - binary_accuracy: 0.9745 - loss: 0.0691 - mse: 0.0192\n",
      "Epoch 23/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 541us/step - binary_accuracy: 0.9750 - loss: 0.0682 - mse: 0.0189\n",
      "Epoch 24/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 569us/step - binary_accuracy: 0.9753 - loss: 0.0674 - mse: 0.0187\n",
      "Epoch 25/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 574us/step - binary_accuracy: 0.9756 - loss: 0.0667 - mse: 0.0185\n",
      "Epoch 26/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 548us/step - binary_accuracy: 0.9757 - loss: 0.0660 - mse: 0.0184\n",
      "Epoch 27/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 540us/step - binary_accuracy: 0.9759 - loss: 0.0654 - mse: 0.0182\n",
      "Epoch 28/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 505us/step - binary_accuracy: 0.9760 - loss: 0.0649 - mse: 0.0181\n",
      "Epoch 29/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 551us/step - binary_accuracy: 0.9762 - loss: 0.0643 - mse: 0.0179\n",
      "Epoch 30/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 535us/step - binary_accuracy: 0.9763 - loss: 0.0638 - mse: 0.0178\n",
      "Epoch 31/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 588us/step - binary_accuracy: 0.9764 - loss: 0.0634 - mse: 0.0177\n",
      "Epoch 32/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 543us/step - binary_accuracy: 0.9767 - loss: 0.0629 - mse: 0.0176\n",
      "Epoch 33/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 561us/step - binary_accuracy: 0.9768 - loss: 0.0625 - mse: 0.0175\n",
      "Epoch 34/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 508us/step - binary_accuracy: 0.9770 - loss: 0.0621 - mse: 0.0174\n",
      "Epoch 35/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 513us/step - binary_accuracy: 0.9771 - loss: 0.0618 - mse: 0.0173\n",
      "Epoch 36/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 560us/step - binary_accuracy: 0.9772 - loss: 0.0614 - mse: 0.0172\n",
      "Epoch 37/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 551us/step - binary_accuracy: 0.9773 - loss: 0.0611 - mse: 0.0171\n",
      "Epoch 38/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 536us/step - binary_accuracy: 0.9775 - loss: 0.0608 - mse: 0.0170\n",
      "Epoch 39/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 548us/step - binary_accuracy: 0.9775 - loss: 0.0605 - mse: 0.0170\n",
      "Epoch 40/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 535us/step - binary_accuracy: 0.9776 - loss: 0.0602 - mse: 0.0169\n",
      "Epoch 41/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 574us/step - binary_accuracy: 0.9777 - loss: 0.0599 - mse: 0.0168\n",
      "Epoch 42/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 579us/step - binary_accuracy: 0.9778 - loss: 0.0596 - mse: 0.0167\n",
      "Epoch 43/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 583us/step - binary_accuracy: 0.9778 - loss: 0.0594 - mse: 0.0167\n",
      "Epoch 44/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 569us/step - binary_accuracy: 0.9779 - loss: 0.0591 - mse: 0.0166\n",
      "Epoch 45/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 587us/step - binary_accuracy: 0.9780 - loss: 0.0589 - mse: 0.0166\n",
      "Epoch 46/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 551us/step - binary_accuracy: 0.9781 - loss: 0.0587 - mse: 0.0165\n",
      "Epoch 47/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 570us/step - binary_accuracy: 0.9781 - loss: 0.0584 - mse: 0.0164\n",
      "Epoch 48/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 554us/step - binary_accuracy: 0.9782 - loss: 0.0582 - mse: 0.0164\n",
      "Epoch 49/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 531us/step - binary_accuracy: 0.9782 - loss: 0.0580 - mse: 0.0163\n",
      "Epoch 50/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 550us/step - binary_accuracy: 0.9783 - loss: 0.0578 - mse: 0.0163\n",
      "Epoch 51/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 545us/step - binary_accuracy: 0.9784 - loss: 0.0576 - mse: 0.0162\n",
      "Epoch 52/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 540us/step - binary_accuracy: 0.9785 - loss: 0.0575 - mse: 0.0162\n",
      "Epoch 53/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 579us/step - binary_accuracy: 0.9785 - loss: 0.0573 - mse: 0.0162\n",
      "Epoch 54/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 550us/step - binary_accuracy: 0.9785 - loss: 0.0571 - mse: 0.0161\n",
      "Epoch 55/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 589us/step - binary_accuracy: 0.9786 - loss: 0.0569 - mse: 0.0161\n",
      "Epoch 56/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 505us/step - binary_accuracy: 0.9786 - loss: 0.0568 - mse: 0.0160\n",
      "Epoch 57/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 519us/step - binary_accuracy: 0.9787 - loss: 0.0566 - mse: 0.0160\n",
      "Epoch 58/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 537us/step - binary_accuracy: 0.9787 - loss: 0.0565 - mse: 0.0160\n",
      "Epoch 59/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 526us/step - binary_accuracy: 0.9787 - loss: 0.0563 - mse: 0.0159\n",
      "Epoch 60/60\n",
      "\u001b[1m479/479\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 578us/step - binary_accuracy: 0.9788 - loss: 0.0562 - mse: 0.0159\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-08-09 14:58:56.385259: W tensorflow/core/framework/op_kernel.cc:1840] OP_REQUIRES failed at xla_ops.cc:577 : INVALID_ARGUMENT: Matrix size-incompatible: In[0]: [1,260], In[1]: [101,20]\n",
      "\n",
      "Stack trace for op definition: \n",
      "File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "File \"<frozen runpy>\", line 88, in _run_code\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 542, in dispatch_queue\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 531, in process_one\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 359, in execute_request\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 775, in execute_request\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 446, in do_execute\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3051, in run_cell\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3106, in _run_cell\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3311, in run_cell_async\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3493, in run_ast_nodes\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n",
      "File \"/tmp/ipykernel_39425/1703203400.py\", line 40, in <module>\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 429, in evaluate\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 165, in one_step_on_iterator\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 154, in one_step_on_data\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 82, in test_step\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/layers/layer.py\", line 882, in __call__\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/ops/operation.py\", line 46, in __call__\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/models/sequential.py\", line 209, in call\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/models/functional.py\", line 175, in call\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/ops/function.py\", line 171, in _run_through_graph\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/models/functional.py\", line 556, in call\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/layers/layer.py\", line 882, in __call__\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/ops/operation.py\", line 46, in __call__\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/layers/core/dense.py\", line 144, in call\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/ops/numpy.py\", line 3445, in matmul\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/numpy.py\", line 477, in matmul\n",
      "\n",
      "\t [[{{node sequential_1/dense_1/MatMul}}]]\n",
      "\ttf2xla conversion failed while converting __inference_one_step_on_data_96371[]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.\n",
      "2024-08-09 14:58:56.385289: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: INVALID_ARGUMENT: Matrix size-incompatible: In[0]: [1,260], In[1]: [101,20]\n",
      "\n",
      "Stack trace for op definition: \n",
      "File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "File \"<frozen runpy>\", line 88, in _run_code\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/asyncio/events.py\", line 80, in _run\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 542, in dispatch_queue\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 531, in process_one\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 359, in execute_request\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 775, in execute_request\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 446, in do_execute\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3051, in run_cell\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3106, in _run_cell\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3311, in run_cell_async\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3493, in run_ast_nodes\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n",
      "File \"/tmp/ipykernel_39425/1703203400.py\", line 40, in <module>\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 429, in evaluate\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 165, in one_step_on_iterator\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 154, in one_step_on_data\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 82, in test_step\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/layers/layer.py\", line 882, in __call__\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/ops/operation.py\", line 46, in __call__\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/models/sequential.py\", line 209, in call\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/models/functional.py\", line 175, in call\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/ops/function.py\", line 171, in _run_through_graph\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/models/functional.py\", line 556, in call\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/layers/layer.py\", line 882, in __call__\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/ops/operation.py\", line 46, in __call__\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/layers/core/dense.py\", line 144, in call\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/ops/numpy.py\", line 3445, in matmul\n",
      "File \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/numpy.py\", line 477, in matmul\n",
      "\n",
      "\t [[{{node sequential_1/dense_1/MatMul}}]]\n",
      "\ttf2xla conversion failed while converting __inference_one_step_on_data_96371[]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.\n",
      "\t [[StatefulPartitionedCall]]\n"
     ]
    },
    {
     "ename": "InvalidArgumentError",
     "evalue": "Graph execution error:\n\nDetected at node sequential_1/dense_1/MatMul defined at (most recent call last):\n<stack traces unavailable>\nMatrix size-incompatible: In[0]: [1,260], In[1]: [101,20]\n\nStack trace for op definition: \nFile \"<frozen runpy>\", line 198, in _run_module_as_main\nFile \"<frozen runpy>\", line 88, in _run_code\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel_launcher.py\", line 18, in <module>\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 739, in start\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\nFile \"/home/mcb/miniconda3/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\nFile \"/home/mcb/miniconda3/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\nFile \"/home/mcb/miniconda3/lib/python3.11/asyncio/events.py\", line 80, in _run\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 542, in dispatch_queue\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 531, in process_one\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 359, in execute_request\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 775, in execute_request\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 446, in do_execute\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3051, in run_cell\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3106, in _run_cell\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3311, in run_cell_async\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3493, in run_ast_nodes\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\nFile \"/tmp/ipykernel_39425/1703203400.py\", line 40, in <module>\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 429, in evaluate\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 165, in one_step_on_iterator\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 154, in one_step_on_data\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 82, in test_step\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/layers/layer.py\", line 882, in __call__\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/ops/operation.py\", line 46, in __call__\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/models/sequential.py\", line 209, in call\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/models/functional.py\", line 175, in call\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/ops/function.py\", line 171, in _run_through_graph\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/models/functional.py\", line 556, in call\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/layers/layer.py\", line 882, in __call__\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/ops/operation.py\", line 46, in __call__\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/layers/core/dense.py\", line 144, in call\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/ops/numpy.py\", line 3445, in matmul\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/numpy.py\", line 477, in matmul\n\n\t [[{{node sequential_1/dense_1/MatMul}}]]\n\ttf2xla conversion failed while converting __inference_one_step_on_data_96371[]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.\n\t [[StatefulPartitionedCall]] [Op:__inference_one_step_on_iterator_96398]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[3], line 40\u001b[0m\n\u001b[1;32m     37\u001b[0m                     runtime \u001b[38;5;241m=\u001b[39m end_time \u001b[38;5;241m-\u001b[39m start_time\n\u001b[1;32m     39\u001b[0m                     loss_train, accuracy_train, mse_train \u001b[38;5;241m=\u001b[39m model\u001b[38;5;241m.\u001b[39mevaluate(X, Y, verbose\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m0\u001b[39m) \n\u001b[0;32m---> 40\u001b[0m                     loss_test, accuracy_test, mse_test \u001b[38;5;241m=\u001b[39m \u001b[43mmodel\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mevaluate\u001b[49m\u001b[43m(\u001b[49m\u001b[43mXX\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;241;43m~\u001b[39;49m\u001b[43mtest_word_indices\u001b[49m\u001b[43m]\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mYY\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;241;43m~\u001b[39;49m\u001b[43mtest_word_indices\u001b[49m\u001b[43m]\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mverbose\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m0\u001b[39;49m\u001b[43m)\u001b[49m \n\u001b[1;32m     42\u001b[0m                     f\u001b[38;5;241m.\u001b[39mwrite(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m,\u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m,\u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m,\u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m,\u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m,\u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m,\u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m,\u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m,\u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m,\u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m,\u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39mformat(\n\u001b[1;32m     43\u001b[0m                                                     hidden,\n\u001b[1;32m     44\u001b[0m                                                     learning_rate,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     52\u001b[0m                                                     mse_test,\n\u001b[1;32m     53\u001b[0m                                                     runtime))\n\u001b[1;32m     54\u001b[0m f\u001b[38;5;241m.\u001b[39mclose()\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py:122\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    119\u001b[0m     filtered_tb \u001b[38;5;241m=\u001b[39m _process_traceback_frames(e\u001b[38;5;241m.\u001b[39m__traceback__)\n\u001b[1;32m    120\u001b[0m     \u001b[38;5;66;03m# To get the full stack trace, call:\u001b[39;00m\n\u001b[1;32m    121\u001b[0m     \u001b[38;5;66;03m# `keras.config.disable_traceback_filtering()`\u001b[39;00m\n\u001b[0;32m--> 122\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m    123\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m    124\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.11/site-packages/tensorflow/python/eager/execute.py:53\u001b[0m, in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     51\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m     52\u001b[0m   ctx\u001b[38;5;241m.\u001b[39mensure_initialized()\n\u001b[0;32m---> 53\u001b[0m   tensors \u001b[38;5;241m=\u001b[39m pywrap_tfe\u001b[38;5;241m.\u001b[39mTFE_Py_Execute(ctx\u001b[38;5;241m.\u001b[39m_handle, device_name, op_name,\n\u001b[1;32m     54\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[1;32m     55\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m core\u001b[38;5;241m.\u001b[39m_NotOkStatusException \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     56\u001b[0m   \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mInvalidArgumentError\u001b[0m: Graph execution error:\n\nDetected at node sequential_1/dense_1/MatMul defined at (most recent call last):\n<stack traces unavailable>\nMatrix size-incompatible: In[0]: [1,260], In[1]: [101,20]\n\nStack trace for op definition: \nFile \"<frozen runpy>\", line 198, in _run_module_as_main\nFile \"<frozen runpy>\", line 88, in _run_code\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel_launcher.py\", line 18, in <module>\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/kernelapp.py\", line 739, in start\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/tornado/platform/asyncio.py\", line 195, in start\nFile \"/home/mcb/miniconda3/lib/python3.11/asyncio/base_events.py\", line 607, in run_forever\nFile \"/home/mcb/miniconda3/lib/python3.11/asyncio/base_events.py\", line 1922, in _run_once\nFile \"/home/mcb/miniconda3/lib/python3.11/asyncio/events.py\", line 80, in _run\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 542, in dispatch_queue\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 531, in process_one\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 359, in execute_request\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py\", line 775, in execute_request\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py\", line 446, in do_execute\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3051, in run_cell\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3106, in _run_cell\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3311, in run_cell_async\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3493, in run_ast_nodes\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\nFile \"/tmp/ipykernel_39425/1703203400.py\", line 40, in <module>\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 429, in evaluate\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 165, in one_step_on_iterator\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 154, in one_step_on_data\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/trainer.py\", line 82, in test_step\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/layers/layer.py\", line 882, in __call__\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/ops/operation.py\", line 46, in __call__\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/models/sequential.py\", line 209, in call\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/models/functional.py\", line 175, in call\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/ops/function.py\", line 171, in _run_through_graph\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/models/functional.py\", line 556, in call\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/layers/layer.py\", line 882, in __call__\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/ops/operation.py\", line 46, in __call__\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py\", line 156, in error_handler\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/layers/core/dense.py\", line 144, in call\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/ops/numpy.py\", line 3445, in matmul\nFile \"/home/mcb/miniconda3/lib/python3.11/site-packages/keras/src/backend/tensorflow/numpy.py\", line 477, in matmul\n\n\t [[{{node sequential_1/dense_1/MatMul}}]]\n\ttf2xla conversion failed while converting __inference_one_step_on_data_96371[]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.\n\t [[StatefulPartitionedCall]] [Op:__inference_one_step_on_iterator_96398]"
     ]
    }
   ],
   "source": [
    "seed = 323\n",
    "\n",
    "\n",
    "\n",
    "with open('outputs/tune_top_500_v2.csv', 'w') as f:\n",
    "    f.write(\"{},{},{},{},{},{},{},{},{},{},{}\\n\".format(\n",
    "                                            \"hidden_units\",\n",
    "                                            \"learning_rate\",\n",
    "                                             \"batch_size\",\n",
    "                                             \"epochs\",\n",
    "                                             \"loss_train\",\n",
    "                                             \"accuracy_train\",\n",
    "                                             \"mse_train\",\n",
    "                                             \"loss_test\",\n",
    "                                             \"accuracy_test\",\n",
    "                                             \"mse_test\",\n",
    "                                             \"time\"))\n",
    "    for learning_rate in [.001, .005, None]: \n",
    "        for batch_size in [6, 8, 10]:\n",
    "            for epochs in [60, 80, 100]:\n",
    "                for hidden in [20, 25, 30, 40]:\n",
    "                    \n",
    "                    print(\"Configuration currently training:\", learning_rate, batch_size, epochs, hidden)\n",
    "\n",
    "                    if learning_rate is not None:\n",
    "                        optimizer = Adam(learning_rate=learning_rate)\n",
    "                    if learning_rate is None:\n",
    "                        optimzer = None\n",
    "\n",
    "                    model = learner(X, Y, seed, hidden, optimizer=None)\n",
    "                    \n",
    "                    start_time = time.time()\n",
    "\n",
    "                    model.fit(X[train_word_indices], Y[train_word_indices], epochs=epochs, batch_size=batch_size, verbose=True)\n",
    "\n",
    "                    end_time = time.time()\n",
    "                    runtime = end_time - start_time\n",
    "\n",
    "                    loss_train, accuracy_train, mse_train = model.evaluate(X[train_word_indices], Y[train_word_indices], verbose=0) \n",
    "                    loss_test, accuracy_test, mse_test = model.evaluate(X[~train_word_indices], Y[~train_word_indices], verbose=0) \n",
    "\n",
    "                    f.write(\"{},{},{},{},{},{},{},{},{},{},{}\\n\".format(\n",
    "                                                    hidden,\n",
    "                                                    learning_rate,\n",
    "                                                    batch_size,\n",
    "                                                    epochs,\n",
    "                                                    loss_train,\n",
    "                                                    accuracy_train,\n",
    "                                                    mse_train,\n",
    "                                                    loss_test,\n",
    "                                                    accuracy_test,\n",
    "                                                    mse_test,\n",
    "                                                    runtime))\n",
    "f.close()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "p39",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
